version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 992002
      POSTGRES_DB: jwat_nest_practice
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # app:
  #   image: rockyoperation/hao-nest-app:1.0
  #   ports:
  #     - 3000:3009
  #   environment:
  #     DATABASE_URI: mongodb://admin:admin@mongo:27017/?authMechanism=DEFAULT
  #     PORT: 3009
    # depends_on:
    #   - postgres

volumes:
  postgres-data:
  